import numpy as np
import pandas as pd
from pathlib import Path
import os
import stable_baselines3 as sb3

def scale(real_value, type):
    """Takes a value in real space and converts it to gym space

    Args:
        real_value (float): value in the real-scaled system
        type (string): Options: "power" or "dpower" or "dtheta" or "drum_angles"

    Returns:
        array or float: value scaled for the gym system
    """
    if type == "power":
        # real bounds are 0 to 22 MW, gym bounds are 0 to 1
        return real_value / 22
    elif type == "dpower":
        # real bounds are -22 to 22 MW/s # CHANGE THIS LATER USING PROMPT JUMP, gym bounds are -1 to 1
        return real_value / 22
    elif type == "dtheta":
        # real bounds are -0.5 deg/s to 0.5 deg/s, gym bounds are -1 to 1
        return real_value * 2
    elif type == "drum_angles":
        # real bounds are 0 to 180 deg, gym bounds are 0 to 1
        return real_value / 180


def descale(gym_value, type):
    """Takes a value in gym space and converts it to real space

    Args:
        gym_value (float): value in the gym-scaled system
        type (string): Options: "power" or "dpower" or "dtheta"

    Returns:
        float: value in physical system units
    """
    if type == "power":
        # real bounds are 0 to 22 MW, gym bounds are 0 to 1
        return gym_value * 22
    elif type == "dpower":
        # real bounds are -22 to 22 MW/s # CHANGE THIS LATER USING PROMPT JUMP, gym bounds are -1 to 1
        return gym_value * 22
    elif type == "dtheta":
        # real bounds are -0.5 deg/s to 0.5 deg/s, gym bounds are -1 to 1
        return gym_value / 2
    elif type == "drum_angles":
        # real bounds are 0 to 180, gym bounds are 0 to 1
        return gym_value * 180


def metrics(history):
    """Calculates performance metrics based on a history dataframe generated by the holos environment.

    Args:
        history (pd.DataFrame): Contains --> "time",
                    "observed_power",
                    "desired_power",
                    "drum_1",
                    "drum_2",
                    "drum_3",
                    "drum_4",
                    "drum_5",
                    "drum_6",
                    "drum_7",
                    "drum_8",
                    "actual_power",
                    "c1",
                    "c2",
                    "c3",
                    "c4",
                    "c5",
                    "c6",
                    "Tf",
                    "Tm",
                    "Tc",
                    "Xe",
                    "I",
    """
    if len(history) == 0:
        raise ValueError("metrics() received an empty history dataframe.")
    error = history["desired_power"] - history["actual_power"]
    absolute_error = np.abs(error)
    mae = np.mean(absolute_error)
    cumulative_abs_error = np.sum(absolute_error)
    drum_angles = history[
        ["drum_1", "drum_2", "drum_3", "drum_4", "drum_5", "drum_6", "drum_7", "drum_8"]
    ]
    drum_speeds = np.diff(drum_angles, axis=0)
    absolute_drum_speeds = np.abs(drum_speeds)
    control_effort = np.sum(absolute_drum_speeds)
    mean_control_effort = control_effort / len(history)
    return mae, cumulative_abs_error, control_effort, mean_control_effort


def find_latest_file(folder_path, pattern="*"):
    """Gets the latest file in a path, specifically for grabbing the best trained RL model.

    Args:
        folder_path (Path): path to folder of interest
        pattern (str, optional): string pattern of file names to search for. Defaults to '*'.

    Returns:
        file: file of interest
    """
    try:
        latest_file = sorted(
            folder_path.glob(pattern), key=os.path.getmtime, reverse=True
        )[0]
        return latest_file
    except IndexError:
        raise FileNotFoundError(
            f"No files matching '{pattern}' in '{folder_path}'. "
            "Please ensure models and their associated files have been generated first."
        )


def get_run_folder(run_type, base=Path.cwd() / "runs"):
    """Creates a run folder based on the run_type ("multi-rl", "single-rl", "marl", etc.)

    Args:
        run_type (string): Run name, such as "multi-rl", "single-rl", "marl"
        base (Path, optional): Path to put the run folder in. Defaults to Path.cwd()/'runs'.

    Returns:
        Path: a path to the run folder
    """
    run_folder = base / run_type
    run_folder.mkdir(exist_ok=True, parents=True)
    return run_folder


def episode_length_within_max_time(profile, episode_length, dt):
    max_time = profile.x[-1]
    episode_time = episode_length * dt
    if episode_time > max_time:
        return False
    else:
        return True

def check_spec(history):
    """Checks if a rollout's power trajectory stays within 3% (relative) of desired power.

    Args:
        history (pd.DataFrame): rollout history with 'actual_power' and 'desired_power' columns

    Returns:
        bool: True if actual power never deviates >=3% (relative) from desired power
    """
    pct_dev = np.abs(
        (history["actual_power"] - history["desired_power"]) / history["desired_power"]
    )
    return (pct_dev < 0.03).all()

def percent_diff(ptrue, pdesired):
    return abs(ptrue - pdesired)/pdesired

def load_trained_model(load_dir="train_fivemillion"):
    """Loads a trained model

    Args:
        load_dir (str): Name of folder where models dir is 

    Returns:
        sb3 model
    """
    model_folder = "runs" / Path(load_dir) / "models/"
    model_path = find_latest_file(model_folder, pattern="*.zip")
    model = sb3.PPO.load(model_path, device="cpu")
    return model


def robustness(p_actual, p_desired, p_threshold):
    """Calculates the robustness of a trajectory defined by the actual power and the desired power for all timesteps. This is based on signal temporal logic.

    Args:
        p_actual (array): Actual achieved power
        p_desired (array): Desired power at corresponding times to p_actual
        p_threshold (float): power specification as a percent deviation from profile
    """
    # if we're at a terminal node, we won't get power arrays, so return infinity (we're going to take a min of this rho and the path rho, so path rho will always get picked if we're at a terminal node)
    if type(p_actual) != list:
        p_actual = np.array([p_actual])
    if type(p_desired) != list:
        p_desired = np.array([p_desired])
    if len(p_actual) == 0:
        return np.inf
    percent_diffs = abs(np.array(p_actual) - np.array(p_desired))/np.array(p_desired)
    rho = np.min(p_threshold - percent_diffs)
    return rho

# check an operational spec on the drums!!