"""
This code was modified from that created for the following publication:

Leo Tunkle, Kamal Abdulraheem, Linyu Lin, Majdi I. Radaideh,
Nuclear microreactor transient and load-following control with deep reinforcement learning,
Energy Conversion and Management: X,
Volume 27,
2025,
101090,
ISSN 2590-1745,
https://doi.org/10.1016/j.ecmx.2025.101090.

Tunkle et al.'s original codebase available at: https://github.com/aims-umich/microdrum-marl.
"""

import time
import numpy as np
import pandas as pd
from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d
import gymnasium as gym
from pke import HolosPK
from pathlib import Path
import warnings
from accessories import scale, descale
import fuzzing

class Undisturbed(gym.Wrapper):
    """Wraps HolosMulti with the standard single-arg step()/reset() signatures
    gym/SB3 expect, always passing a zero disturbance. Use this for nominal
    training; use HolosMulti directly (with an explicit
    Disturbance every step) for testing fuzzing and falsification search.
    
    This class & docstring was generated by Claude Sonnet 5, but modified and verified by Nataly."""

    ZERO_DISTURBANCE = fuzzing.Disturbance(
        xo={"dp": 0, "p": 0, "drum_angles": np.zeros(8)},
        xa=np.zeros(8),
        xs=np.zeros(12),
    )

    def step(self, action):
        return self.env.step(action, disturbance=self.ZERO_DISTURBANCE)

def make_undisturbed_env(env_type, **kwargs):
    # generates undisturbed holos environments for training
    return Undisturbed(env_type(**kwargs))

class HolosMulti(gym.Env):
    def __init__(
        self,
        profile,
        episode_length,
        training=True,
        max_failed_drums=1,
        dt=1,
        save_dir="./run_histories",
    ):
        """Initializes the HolosMulti environment

        Args:
            profile (interp1d function): callable function to yield the desired power (y) at any given time (x) as a fraction of the total reactor power.
            episode_length (int): Number of timesteps in the episode (NOT seconds, this is just a count)
            training (bool): Whether the run is for training or testing.
            max_failed_drums (int): The maximum number of drums allowed to randomly fail.
            dt (int, optional): Number of seconds in a step. Defaults to 1 second.
            save_dir (str, optional): Directory to save the run.
        """
        self.profile = profile
        self.episode_length = episode_length
        self.training = training
        if training:
            self.max_failed_drums = 0
        else:
            self.max_failed_drums = max_failed_drums
        self.dt = dt
        self.save_dir = Path(save_dir)
        # make the save_dir a directory if it's not already
        try:
            self.save_dir.mkdir(parents=True, exist_ok=True)
        except FileExistsError:
            warnings.warn(
                f"'{self.save_dir}' is a file, not a directory. Falling back to default."
            )
            self.save_dir = Path("./run_histories")
            self.save_dir.mkdir(parents=True, exist_ok=True)
        # number of seconds in an episode
        # we subtract dt here otherwise the algorithm will try to loop out of the defined power profile
        self.runtime = episode_length * dt - dt
        # initialize a point kinetics model
        self.pke = HolosPK()
        # initialize starting states
        self._dp = 0  # starting power rate of change, assume 0 at steady state
        self._p = 1  # starting power (as a fraction of total power)), assume reactor starts at full power steady state
        self._pnext = self.profile(0)  # next desired power (fraction)
        self._drum_angles = np.array([77.8] * 8)

        self.observation_space = gym.spaces.Dict(
            {
                "dp": gym.spaces.Box(low=-1, high=1, shape=(1,), dtype=np.float32),
                "p": gym.spaces.Box(low=0, high=1, shape=(1,), dtype=np.float32),
                "pnext": gym.spaces.Box(low=0, high=1, shape=(1,), dtype=np.float32),
                "drum_angles": gym.spaces.Box(
                    low=0, high=1, shape=(8,), dtype=np.float32
                ),
            }
        )

        self.action_space = gym.spaces.Box(low=-1, high=1, shape=(8,), dtype=np.float32)

    def _get_observation(self, xo, reset=False):
        """Converts internal state to observation format (recommended per gym docs)

        Args:
            xo (dict, optional): observation disturbance with keys dp, p, and drum_angles

        Returns: dp, p, drum angles, pnext as a dictionary

        MUST CALL THIS FUNCTION BEFORE _log_history or indexing will be off!
        """
        if xo["drum_angles"].shape != (8,):
            raise ValueError("Drum angle disturbance must be in the shape (8,)!")
        # fuzz then scale the drum angles, noise should be in physical space
        noisy_drum_angles = scale(self._drum_angles + xo["drum_angles"], "drum_angles")
        # fuzz the current power
        noisy_power = self._p + xo["p"]

        if reset:
            # always assume a steady state start
            self._dp = 0
        else: 
            self._plast = self.history[-1][1] # this is the noisy power from the last timestep
            # get the "observed power rate" using two noisy power readings
            self._dp = (noisy_power - self._plast) / self.dt
        # return everything in a dictionary
        return {
            "dp": np.array([self._dp], dtype=np.float32),
            "p": np.array([noisy_power], dtype=np.float32),
            "pnext": np.array([self._pnext], dtype=np.float32),
            "drum_angles": noisy_drum_angles.astype(np.float32),
        }

    def _log_history(self, observation, init=False):
        if init:
            self.history = [
                [
                    self.time,
                    observation["p"].item(),  # observed power
                    self.profile(self.time),  # desired power
                    *self._drum_angles,
                    *self.state, # includes actual power
                ]
            ]
            return
        else:
            self.history.append(
                [
                    self.time,
                    observation["p"].item(),  # observed power
                    self.profile(self.time),  # desired power
                    *self._drum_angles,
                    *self.state, # actual power is in here
                ]
            )
            return

    def mask_drums(self):
        valid_maskings = tuple(range(self.max_failed_drums + 1))
        num_masks = np.random.choice(valid_maskings)
        self.masks = np.ones(8)
        mask_indices = np.random.choice(8, size=num_masks, replace=False)
        self.masks[mask_indices] = 0
        return

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        # reset starting states
        self.time = 0
        self._pnext = self.profile(
            0 + self.dt
        )  # desired power from profile at first time step
        # we do NOT fuzz the initial conditions here, always assume same IC
        self._drum_angles = np.array([77.8] * 8)
        self.state = self.pke.get_initial_conditions()
        # reminder for state shape: [n_r, c1, c2, c3, c4, c5, c6, Tf, Tm, Tc, xe, i]
        self._p, *_ = (
            self.state
        )  # gets initial power from pke neutron density (assumed equal in this code)
        self.mask_drums()
        # get observation disturbance for the first step via options
        # we have to do this to make it compatible with gym's reqs for reset()
        xo = options["xo"] if options and "xo" in options else {"dp": 0, "p": 0, "drum_angles": np.zeros(8)}
        observation = self._get_observation(xo=xo, reset=True)
        self._log_history(observation=observation, init=True)
        return observation, {}  # return empty dict for info

    def step(self, action, disturbance):
        # increment time by 1 step
        self.time += self.dt
        # convert action to real space with noise added from xa and masks applied. noise should be in physical space!
        real_action = (descale(action, "dtheta") + disturbance.xa) * self.masks 
        # get the linearly interpolated function for the drums
        drum_forcers = self.pke.drum_forcing(self._drum_angles, real_action)
        # update the environment state
        # solve PKE
        sol = solve_ivp(self.pke.reactor_dae, [0, 1], self.state, args=drum_forcers)
        # get the state and add noise with xs
        self.state = sol.y[:, -1] + disturbance.xs
        # update the power level according to new neutron density from PKE
        self._p, *_ = self.state
        # get the next desired power from the profile
        self._pnext = self.profile(self.time + self.dt)
        # update the drum angles
        self._drum_angles += real_action  # unscaled drum angles + real action
        self._drum_angles = np.clip(
            self._drum_angles, 0, 180
        )  # makes sure action leaves drums within physical bounds
        # get the observation
        observation = self._get_observation(xo=disturbance.xo)
        # log the step in history
        self._log_history(observation=observation, init=False)

        # calculate the reward and termination criteria
        reward, terminated = self.calc_reward(
            current_power=self._p, desired_power=self.profile(self.time)
        )
        # check to see if time exceeded
        truncated = False
        if self.time >= self.runtime:
            truncated = True

        return (
            observation,
            reward,
            terminated,
            truncated,
            {},
        )  # return empty dict for info

    def calc_reward(self, current_power, desired_power):
        """Returns reward and whether the episode is terminated."""
        # First component: give reward to stay in the correct range
        diff = 100 * abs(current_power - desired_power)
        assert diff <= 200, "diff out of reasonable bounds"
        reward = 2 - diff

        # give a punish outside bounds if in train mode
        terminated = False
        if self.training and (
            diff > 5 or self._drum_angles.min() <= 0 or self._drum_angles.max() >= 180
        ):
            reward -= 100
            terminated = True

        return reward, terminated

    def render(self, save=True):
        """Converts the history list of lists into a dataframe."""
        run_history = np.array(self.history)
        column_names = [
            "time",
            "observed_power",
            "desired_power",
            "drum_1",
            "drum_2",
            "drum_3",
            "drum_4",
            "drum_5",
            "drum_6",
            "drum_7",
            "drum_8",
            "actual_power",
            "c1",
            "c2",
            "c3",
            "c4",
            "c5",
            "c6",
            "Tf",
            "Tm",
            "Tc",
            "Xe",
            "I",
        ]
        df = pd.DataFrame(run_history, columns=column_names)
        df["diff"] = (df["actual_power"] - df["desired_power"]) * 100

        timestr = time.strftime("%Y%m%d-%H%M%S")
        save_path = self.save_dir / f"run_history_{timestr}.csv"
         
        if save:
            df.to_csv(save_path, index=False)

        return df
