"""
The tests in this script were generated by Claude Sonnet 5 but were modified and verified by the author (Nataly Panczyk).
"""

import gymnasium as gym
import numpy as np
import pandas as pd
import pytest
from unittest.mock import MagicMock, patch, call, ANY

import accessories
import loops
import fuzzing
import env
from scipy.interpolate import interp1d
from functools import partial
from env import make_undisturbed_env
import profiles


# ---------------------------------------------------------------------------
# train_rl
# ---------------------------------------------------------------------------
@pytest.fixture
def env_kwargs():
    return {}


class DummyDictEnv(gym.Env):
    """Minimal Dict-observation env matching HolosMulti's constructor/step
    signature, so it's a valid stand-in for train_rl/test_trained_rl, which
    now assume HolosMulti-shaped envs specifically."""

    def __init__(self, run_path=None, save_dir=None):
        self.observation_space = gym.spaces.Dict(
            {"obs": gym.spaces.Box(low=-1, high=1, shape=(2,), dtype=np.float32)}
        )
        self.action_space = gym.spaces.Discrete(2)
        self._t = 0

    def reset(self, *, seed=None, options=None):
        self._t = 0
        return {"obs": self.observation_space["obs"].sample()}, {}

    def step(self, action, disturbance):
        self._t += 1
        obs = {"obs": self.observation_space["obs"].sample()}
        terminated = self._t >= 3
        return obs, 0.0, terminated, False, {}


def test_train_rl_wires_up_components_correctly(tmp_path, env_kwargs):
    """Mocked: confirms train_rl constructs/configures SB3 objects with the
    right arguments, without actually training."""
    save_dir = tmp_path

    with patch("loops.make_vec_env") as mock_make_vec_env, patch(
        "loops.VecMonitor"
    ) as mock_vec_monitor, patch("loops.Monitor") as mock_monitor, patch(
        "loops.sb3.PPO"
    ) as mock_ppo_cls, patch(
        "loops.EvalCallback"
    ) as mock_eval_cb_cls:

        mock_vec_env = MagicMock()
        mock_make_vec_env.return_value = mock_vec_env
        mock_vec_monitor.return_value = mock_vec_env

        mock_model = MagicMock()
        mock_ppo_cls.return_value = mock_model

        loops.train_rl(
            DummyDictEnv, save_dir, env_kwargs, total_timesteps=5_000, n_envs=10
        )

        # dirs created
        assert (save_dir / "models").exists()

        mock_make_vec_env.assert_called_once()
        call_args = mock_make_vec_env.call_args
        factory = call_args.args[0]
        assert isinstance(factory, partial)
        assert factory.func is make_undisturbed_env
        assert factory.args == (DummyDictEnv,)
        assert call_args.kwargs["n_envs"] == 10
        assert call_args.kwargs["env_kwargs"] == env_kwargs

        # PPO constructed on the (wrapped) vec env
        assert mock_ppo_cls.call_args.args[0] == "MultiInputPolicy"
        assert mock_ppo_cls.call_args.args[1] is mock_vec_env

        # eval_freq: 10_000 / n_envs=10 -> 1000, rounded to nearest 1000
        _, eval_cb_kwargs = mock_eval_cb_cls.call_args
        assert eval_cb_kwargs["eval_freq"] == 1000
        assert eval_cb_kwargs["deterministic"] is True

        # learn() called with total_timesteps and the eval callback
        mock_model.learn.assert_called_once()
        _, learn_kwargs = mock_model.learn.call_args
        assert learn_kwargs["total_timesteps"] == 5_000
        assert learn_kwargs["callback"] is mock_eval_cb_cls.return_value


def test_train_rl_real_smoke_run(tmp_path, env_kwargs):
    """Real (unmocked) end-to-end run: tiny env, tiny total_timesteps,
    n_envs=1. Confirms train_rl actually produces a saved model + logs,
    not just that it calls the right APIs."""
    save_dir = tmp_path

    loops.train_rl(DummyDictEnv, save_dir, env_kwargs, total_timesteps=200, n_envs=1)

    model_files = list((tmp_path / "models").glob("*.zip"))
    assert model_files, "expected EvalCallback to save at least one checkpoint"
    assert (tmp_path / "logs").exists()


# ---------------------------------------------------------------------------
# rl_control_loop
# ---------------------------------------------------------------------------


def test_rl_control_loop_runs_until_terminated_and_renders_once():
    mock_model = MagicMock()
    mock_model.predict.return_value = (0, None)

    mock_env = MagicMock()
    mock_env.reset.return_value = ({"obs": 0}, {})
    mock_env.step.side_effect = [
        ({"obs": 1}, 0.0, False, False, {}),
        ({"obs": 2}, 0.0, False, False, {}),
        ({"obs": 3}, 0.0, True, False, {}),
    ]

    mock_disturbance_dist = MagicMock()
    loops.rollout(mock_model, mock_env, mock_disturbance_dist)

    assert mock_env.step.call_count == 3
    assert mock_model.predict.call_count == 3
    mock_model.predict.assert_called_with({"obs": 2}, deterministic=True)
    mock_env.render.assert_called_once()


def test_rollout_stops_on_truncated():
    mock_model = MagicMock()
    mock_model.predict.return_value = (0, None)

    mock_env = MagicMock()
    mock_env.reset.return_value = ({"obs": 0}, {})
    mock_env.step.return_value = ({"obs": 1}, 0.0, False, True, {})  # truncated

    mock_disturbance_dist = MagicMock()

    loops.rollout(mock_model, mock_env, mock_disturbance_dist)

    assert mock_env.step.call_count == 1
    mock_env.render.assert_called_once()

def test_rollout_applies_observation_noise(tmp_path):
    """Integration check: confirms rollout() -> env.step() -> _get_observation
    actually applies xo, by comparing observed p against true p at each step.
    A continuous Gaussian sample being exactly 0 has probability 0, so any
    nonzero sigma_p should produce a mismatch almost surely."""
    profile = interp1d([0, 5], [1, 1])
    test_env = env.HolosMulti(profile=profile, episode_length=3, save_dir=tmp_path)

    mock_model = MagicMock()
    mock_model.predict.return_value = (np.zeros(8), None)

    disturbance_dist = fuzzing.DisturbanceDistribution(
        Do=fuzzing.Do(sigma_p=0.05, sigma_drum=0.05),
        Da=fuzzing.Da(sigma_dtheta=0),
        Ds=fuzzing.Ds(),
    )

    seen = []
    real_get_observation = test_env._get_observation
    def spy(xo, reset=False):
        obs = real_get_observation(xo, reset=reset)
        seen.append((obs["p"][0], test_env._p))
        return obs
    test_env._get_observation = spy

    loops.rollout(mock_model, test_env, disturbance_dist)

    assert any(not np.isclose(obs_p, true_p) for obs_p, true_p in seen), \
        "Expected observed p to differ from true p due to sensor noise"


# ---------------------------------------------------------------------------
# test_trained_rl
# ---------------------------------------------------------------------------


def test_test_trained_rl_orchestrates_load_run_and_metrics(tmp_path, env_kwargs):
    load_dir = save_dir = tmp_path
    fake_history = pd.DataFrame({"time": [0, 1], "actual_power": [1.0, 1.0]})
    mock_disturbance_dist = MagicMock()

    with patch("loops.load_trained_model") as mock_load_model, \
         patch("loops.find_latest_file") as mock_find_latest, \
         patch("loops.rollout") as mock_control_loop, \
         patch("loops.metrics", return_value=(0.1, 0.2, 0.3, 0.4)) as mock_calc_metrics, \
         patch("loops.pd.read_csv", return_value=fake_history) as mock_read_csv:

        mock_model = MagicMock()
        mock_load_model.return_value = mock_model
        mock_find_latest.return_value = tmp_path / "run_history_001.csv"

        result = loops.test_trained_rl(
            DummyDictEnv, load_dir, save_dir, env_kwargs, mock_disturbance_dist, save_histories=True
        )

        mock_load_model.assert_called_once_with(load_dir)
        mock_control_loop.assert_called_once_with(
            mock_model, ANY, mock_disturbance_dist, save_histories=True
        )
        mock_find_latest.assert_called_once_with(tmp_path, pattern="run_history*.csv")
        mock_read_csv.assert_called_once_with(tmp_path / "run_history_001.csv")
        mock_calc_metrics.assert_called_once_with(fake_history)
        assert result is fake_history

# ---------------------------------------------------------------------------
# test_rollout_from_snapshot
# ---------------------------------------------------------------------------

class StubPolicy:
    """Deterministic policy that depends on the observation (so a wrong restored obs changes the result)."""

    def predict(self, obs, deterministic=True):
        err = float(obs["pnext"][0] - obs["p"][0]) - 2.0 * float(obs["dp"][0])
        return np.full(8, np.clip(5 * err, -1, 1), dtype=np.float32), None


def full_run_max_dev(env, model, dist):
    """Reference: plain reset-to-end rollout, deviation from env.history like check_spec does."""
    obs, _ = env.reset()
    np.random.seed(0)
    done = False
    while not done:
        action, _ = model.predict(obs, deterministic=True)
        x = dist.sample(env.state, action)
        obs, _, term, trunc, _ = env.step(action, x)
        done = term or trunc
    df = env.render(save=False)
    max_dev = float(np.abs((df["actual_power"] - df["desired_power"]) / df["desired_power"]).max())
    return max_dev, env.state.copy()


def check_rollout_from_snapshot(env, model, dist, mid_step=30):
    profile = env.profile
    expected, final_state = full_run_max_dev(env, model, dist)

    # 1) root snapshot reproduces a plain full rollout
    env.reset()
    snap0 = env.get_snapshot()
    np.random.seed(0)
    md, n = loops.rollout_from_snapshot(env, model, snap0, dist, 0)
    assert md == pytest.approx(expected, rel=1e-6)
    assert n == env.runtime  # one simulator step per second, dt=1
    assert np.allclose(env.state, final_state)  # final state is sensitive to every action taken

    # 2) a mid-trajectory snapshot plus start_max reproduces the same result
    obs, _ = env.reset()
    np.random.seed(0)
    mid_max = 0.0
    for _ in range(mid_step):
        action, _ = model.predict(obs, deterministic=True)
        obs, *_ = env.step(action, dist.sample(env.state, action))
        print(f"PROFILE: {profile(env.time)}")
        mid_max = max(mid_max, abs(env._p - profile(env.time)) / profile(env.time))
    snap_mid = env.get_snapshot()
    rng = np.random.get_state()
    obs_back = env.set_snapshot(snap_mid)  # restore should hand back the obs saved with the snapshot
    for k in obs:
        assert np.array_equal(obs_back[k], obs[k]), k

    np.random.set_state(rng)
    md_mid, n_mid = loops.rollout_from_snapshot(env, model, snap_mid, dist, mid_max)
    assert md_mid == pytest.approx(expected, rel=1e-6)
    assert n_mid == env.runtime - mid_step
    assert np.allclose(env.state, final_state)

    # 3) determinism: same snapshot + same RNG state gives an identical result, and the snapshot is not corrupted
    np.random.set_state(rng)
    md_again, _ = loops.rollout_from_snapshot(env, model, snap_mid, dist, mid_max)
    assert md_again == md_mid

    # 4) a snapshot at the end of the episode does nothing
    md_end, n_end = loops.rollout_from_snapshot(env, model, env.get_snapshot(), dist, 0.123)
    assert (md_end, n_end) == (0.123, 0)


def test_rollout_from_snapshot_stub(tmp_path):
    profile = interp1d([0, 10, 70, 100, 115, 125, 150, 180, 200],
                       [1, 1, 0.5, 0.5, 0.65, 0.65, 0.5, 0.8, 0.8])
    holosenv = env.HolosMulti(profile=profile, episode_length=200, training=False,
                     max_failed_drums=0, save_dir=tmp_path)
    dist = fuzzing.DisturbanceDistribution(fuzzing.Do(0.001, 0.005), fuzzing.Da(0), fuzzing.Ds())
    check_rollout_from_snapshot(holosenv, StubPolicy(), dist)


def test_rollout_from_snapshot_trained(tmp_path):
    _, env_kwargs = profiles.get_profile("test", max_failed_drums=0)
    holosenv = env.HolosMulti(**env_kwargs, save_dir=tmp_path)
    dist = fuzzing.DisturbanceDistribution(fuzzing.Do(0.001, 0.005), fuzzing.Da(0), fuzzing.Ds())
    check_rollout_from_snapshot(holosenv, accessories.load_trained_model(), dist)
